export const FE_JOURNEY_PRESET = Object.freeze({
  timezone: 'Asia/Shanghai',
  nowcoder: Object.freeze({
    intervalMs: 24 * 60 * 60 * 1_000,
    failureRetryMs: 60 * 60 * 1_000,
    recoverableFailureCooldownMs: 60 * 60 * 1_000,
    maxPerRun: 24,
    planDiscoveryLimit: 75,
    planPerCompanyDiscoveryLimit: 15,
    planTargetAccepted: 10,
    planInitialRoundSize: 8,
    planRefillRoundSize: 4,
    planDetailBudget: 24,
    queries: Object.freeze([
      'Agent 面经',
      'AI 应用开发 面经',
      'Agent 平台开发',
      'RAG 面试',
      '大模型应用开发',
      'MCP 面试',
      'LangGraph 面试',
    ]),
    companyQueries: Object.freeze([
      { company: 'bytedance', query: '字节 Agent 开发 面经' },
      { company: 'tencent', query: '腾讯 Agent 开发 面经' },
      { company: 'alibaba', query: '阿里 Agent 开发 面经' },
      { company: 'ant', query: '蚂蚁 Agent 开发 面经' },
      { company: 'bytedance', query: '字节 AI 应用开发 面经' },
      { company: 'tencent', query: '腾讯 AI 应用开发 面经' },
      { company: 'alibaba', query: '阿里 AI 应用开发 面经' },
      { company: 'ant', query: '蚂蚁 AI 应用开发 面经' },
      { company: 'bytedance', query: '字节 大模型应用开发 面经' },
      { company: 'tencent', query: '腾讯 大模型应用开发 面经' },
      { company: 'alibaba', query: '阿里 大模型应用开发 面经' },
      { company: 'ant', query: '蚂蚁 大模型应用开发 面经' },
      { company: 'bytedance', query: '字节 RAG 面经' },
      { company: 'tencent', query: '腾讯 RAG 面经' },
      { company: 'alibaba', query: '阿里 RAG 面经' },
      { company: 'ant', query: '蚂蚁 RAG 面经' },
      { company: 'bytedance', query: '字节 MCP 面经' },
      { company: 'tencent', query: '腾讯 MCP 面经' },
      { company: 'alibaba', query: '阿里 MCP 面经' },
      { company: 'ant', query: '蚂蚁 MCP 面经' },
      { company: 'bytedance', query: '字节 AI 全栈 面经' },
      { company: 'tencent', query: '腾讯 AI 全栈 面经' },
      { company: 'alibaba', query: '阿里 AI 全栈 面经' },
      { company: 'ant', query: '蚂蚁 AI 全栈 面经' },
      { company: 'bytedance', query: '字节 Agent 平台 面经' },
      { company: 'tencent', query: '腾讯 Agent 平台 面经' },
      { company: 'alibaba', query: '阿里 Agent 平台 面经' },
      { company: 'ant', query: '蚂蚁 Agent 平台 面经' },
      { company: 'bytedance', query: '字节 Code Agent 面经' },
      { company: 'tencent', query: '腾讯 Code Agent 面经' },
      { company: 'alibaba', query: '阿里 Code Agent 面经' },
      { company: 'ant', query: '蚂蚁 Code Agent 面经' },
      { company: 'bytedance', query: '字节 AI 工程 面经' },
      { company: 'tencent', query: '腾讯 AI 工程 面经' },
      { company: 'alibaba', query: '阿里 AI 工程 面经' },
      { company: 'ant', query: '蚂蚁 AI 工程 面经' },
      { company: 'bytedance', query: '字节 智能体 面经' },
      { company: 'tencent', query: '腾讯 智能体 面经' },
      { company: 'alibaba', query: '阿里 智能体 面经' },
      { company: 'ant', query: '蚂蚁 智能体 面经' },
      { company: 'other', query: '拼多多 Agent 面经' },
      { company: 'other', query: '拼多多 AI 面经' },
      { company: 'other', query: '小红书 Agent 面经' },
      { company: 'other', query: '小红书 AI 面经' },
      { company: 'other', query: '月之暗面 Agent 面经' },
      { company: 'other', query: '月之暗面 AI 面经' },
      { company: 'other', query: '百度 Agent 面经' },
      { company: 'other', query: '百度 AI 面经' },
      { company: 'other', query: '华为 Agent 面经' },
      { company: 'other', query: '华为 AI 面经' },
    ]),
  }),
  github: Object.freeze({
    intervalMs: 7 * 24 * 60 * 60 * 1_000,
    failureRetryMs: 60 * 60 * 1_000,
    maxPerRun: 12,
    queries: Object.freeze([
      'topic:ai-agent stars:>=50 fork:false',
      'topic:rag stars:>=100 fork:false',
      'topic:mcp-server stars:>=20 fork:false',
      'topic:agent-framework stars:>=50 fork:false',
      'topic:llm-app stars:>=50 fork:false',
    ]),
  }),
});
